apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ingress-nginx.name" . }}
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ingress-nginx.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ingress-nginx.name" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ingress-nginx.name" . }}-admission
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ingress-nginx.name" . }}-admission
subjects:
  - kind: ServiceAccount
    name: {{ include "ingress-nginx.name" . }}-admission
    namespace: {{ .Release.Namespace }}