apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-controller
  namespace: {{ .Release.Namespace }}
data:
  {{- toYaml .Values.configmap | nindent 2 }}