apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
  name: {{ include "ingress-nginx.name" . }}-controller
  namespace: {{ .Release.Namespace }}
data:
  allow-snippet-annotations: 'true'