apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.ingressClass }}
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
spec:
  controller: {{ .Release.Namespace }}/{{ include "ingress-nginx.name" . }}