apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.ingressClass.name | default "nginx" }}
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
spec:
  controller: "k8s.io/ingress-nginx"