apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ingress-nginx.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ingress-nginx.name" . }}-admission
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}