# permissions for end users to view nginxingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nginxingress-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ingress-nginx-helm-operator
    app.kubernetes.io/part-of: ingress-nginx-helm-operator
    app.kubernetes.io/managed-by: kustomize
  name: nginxingress-viewer-role
rules:
- apiGroups:
  - charts.nginx.org.nginx.io
  resources:
  - nginxingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.nginx.org.nginx.io
  resources:
  - nginxingresses/status
  verbs:
  - get
