apiVersion: charts.nginx.org.nginx.io/v1alpha1
kind: NginxIngress
metadata:
  name: demo
spec:
  # Default values copied from <project_dir>/helm-charts/ingress-nginx/values.yaml
  affinity: {}
  fullnameOverride: ""
  image:
    pullPolicy: IfNotPresent
    repository: k8s.gcr.io/ingress-nginx/controller
    tag: v0.49.3
  imagePullSecrets: []
  nameOverride: ""
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  replicaCount: 1
  resources: {}
  service:
    nodePorts:
      http: "30080"
      https: "30443"
    type: NodePort
  tolerations: []
  
  
