apiVersion: charts.nginx.org.nginx.io/v1alpha1
kind: NginxIngress
metadata:
  name: nginxingress-sample
spec:
  # Default values copied from <project_dir>/helm-charts/ingress-nginx/values.yaml
  affinity: {}
  configmap:
    access-log-path: /var/log/nginx/access.log
    allow-snippet-annotations: "true"
    error-log-path: /var/log/nginx/error.log
    proxy-connect-timeout: "5"
    proxy-read-timeout: "60"
    proxy-send-timeout: "60"
    upstream-keepalive-connections: "320"
    upstream-keepalive-requests: "1000"
    upstream-keepalive-timeout: "15"
  fullnameOverride: ""
  image:
    pullPolicy: IfNotPresent
    repository: k8s.gcr.io/ingress-nginx/controller
    tag: v0.49.3
  imagePullSecrets: []
  ingressClass:
    name: nginx
  nameOverride: ""
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  replicaCount: 1
  resources: {}
  service:
    type: ClusterIP
  tolerations: []
  
  
